// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjvkF2oR-s7vM1u8913myTnYfFjZ0GhQI',
    appId: '1:714826422482:web:330bc6fb8a53c5a39f750b',
    messagingSenderId: '714826422482',
    projectId: 'agrigeo01-5859',
    authDomain: 'agrigeo01-5859.firebaseapp.com',
    storageBucket: 'agrigeo01-5859.firebasestorage.app',
    measurementId: 'G-7W1PDBMX03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zEK-yozjAoEJQB_IJ4TU2yJ6VHyogDE',
    appId: '1:714826422482:android:6277ac09a4799cea9f750b',
    messagingSenderId: '714826422482',
    projectId: 'agrigeo01-5859',
    storageBucket: 'agrigeo01-5859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmNmCHRo6qu4KFiYoO4UgsDs9jwnGy1DE',
    appId: '1:714826422482:ios:422f147e831e51a79f750b',
    messagingSenderId: '714826422482',
    projectId: 'agrigeo01-5859',
    storageBucket: 'agrigeo01-5859.firebasestorage.app',
    iosBundleId: 'com.example.appAgrigeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmNmCHRo6qu4KFiYoO4UgsDs9jwnGy1DE',
    appId: '1:714826422482:ios:422f147e831e51a79f750b',
    messagingSenderId: '714826422482',
    projectId: 'agrigeo01-5859',
    storageBucket: 'agrigeo01-5859.firebasestorage.app',
    iosBundleId: 'com.example.appAgrigeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjvkF2oR-s7vM1u8913myTnYfFjZ0GhQI',
    appId: '1:714826422482:web:357191b887d2774e9f750b',
    messagingSenderId: '714826422482',
    projectId: 'agrigeo01-5859',
    authDomain: 'agrigeo01-5859.firebaseapp.com',
    storageBucket: 'agrigeo01-5859.firebasestorage.app',
    measurementId: 'G-0MZ82RHRMN',
  );
}
